databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
 - type: redis
   name: cache
   ipAllowList: [] # only allow internal connections
   plan: free # optional (defaults to starter)
   maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL # this must match the name of the environment variable used in production.rb
          fromService:
            type: redis
             name: cache
             property: connectionString